### ISSUE TITLE
-s does not seem to produce a source map

### ISSUE THREAD

**Issue by aappddeevv** [scala-js/scala-js-cli#29]
I'm wondering if I am calling it wrong, but when I use `-s` no source map is produced e.g. `scalajsld -s -r -d -f -K ESModule -o blah.js <classpath stuff>`. I get a .js file with everything in it but no source map is next to it, e.g., `blah.js.map` and there is no source map reference at the bottom of blah.js.

**Comment by gzm0** [comment]
Clearly a bug. The call to linker does not even attempt to pass a source map file.

**Comment by aappddeevv** [comment]
Is it possible to have some way to pass the linked file and map through a callback in the driver program?  I would not mind having the opportunity to post-process the map file before it gets written. I could not tell if there is any API for that already. It would be nice to capture it while in memory versus post processing and having to do IO.

**Comment by gzm0** [comment]
Well this seems kind of OT on this issue, but you can simply use the linker API directly. It is not very complicated (have a look at the CLI code).

**Comment by aappddeevv** [comment]
Tested changed and it worked. Thanks!

**Comment by gzm0** [comment]
Re-opening this, since the relevant PR is not merged yet.
