### ISSUE TITLE
scalajsc fails on windows upon first invocation

### ISSUE THREAD

**Issue by gzm0** [scala-js/scala-js-cli#34]
The first invocation after `scalajsc` has been added to the path, it seems to not find the Scala.js library (log follows). The next invocation works as expected.

How to reproduce (use `foo.scala` from test cases):

```
> set PATH=%PATH%;<...>
> scalajsc foo.scala
```

**Comment by gzm0** [comment]
Test log

```
>set PATH=%PATH%;...\scalajs_2.11\bin;...\scala-2.11.1\bin

>cd tmp

tmp>dir
 Volume in drive E is PersistentDataDisk
 Volume Serial Number is 8093-8FED

 Directory of tmp

28.05.2014  15:37    <DIR>          .
28.05.2014  15:37    <DIR>          ..
28.05.2014  15:36    <DIR>          bin
28.05.2014  15:36               210 foo.scala
28.05.2014  15:37           506'336 test.js
               2 File(s)        506'546 bytes
               3 Dir(s)   1'862'295'552 bytes free

tmp>scalajsc foo.scala
foo.scala:1: error: object scalajs is not a member of package scala
import scala.scalajs.js.JSApp
             ^
foo.scala:2: error: not found: type JSApp
          object Foo extends JSApp {
                             ^
two errors found

tmp>scalajsc foo.scala

>
```

**Comment by sjrd** [comment]
Rescheduling this for 0.5.1. It's really not important. We can tell the very small intersection of developers using the CLI and Windows that it might fail on the first invocation in Known Issues.

**Comment by gzm0** [comment]
Note that his also happens if `scalajsc` is in the user path upon startup of `cmd.exe`.

**Comment by gzm0** [comment]
Could someone please test this independently, I'm running this in a VM and it wouldn't astonish me at all if it is a file share issue or something.

**Comment by sjrd** [comment]
I'll do that tonight if I don't forget.

**Comment by sjrd** [comment]
Well, seems it behaves exactly the same way on perfectly genuine, stand-alone Windows 8.1 installation.

**Comment by gzm0** [comment]
:( any windows gurus around?

**Comment by gzm0** [comment]
@sjrd I propose we move this to 0.5.2 so we get 0.5.1 free to release.

**Comment by sjrd** [comment]
Yes ok

**Comment by gzm0** [comment]
Putting on hold until someone actually complains
